services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/noteskeeper
      - JWT_SECRET=secret
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules # Prevent overwriting node_modules
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
